/*
 * 中泰語言學習網站 —— 資料表建立腳本
 *
 * 資料庫：PostgreSQL 15 以上 / language_project
 * 執行方式見本檔最下方說明。
 *
 * ── 文字編碼：PostgreSQL 不需要區分 NVARCHAR 與 VARCHAR ────────────────
 * 舊版（SQL Server）在這裡有一大段警告：collation 為 Latin1 時，
 * VARCHAR 無法保存中文與泰文，存進去會靜默變成「?」，且不會拋出任何錯誤。
 *
 * PostgreSQL 預設編碼為 UTF-8，VARCHAR 本身就能完整保存中文、泰文、
 * 拼音聲調符號，沒有第二種文字型別要選。原本那個坑在這裡不存在。
 *
 * ★ 但這段歷史仍然值得記住：換資料庫時「型別看起來一樣、行為卻不同」
 *   是最難發現的一類問題，因為它不會報錯。
 * ──────────────────────────────────────────────────────────────────
 *
 * ── 音檔存在哪裡 ────────────────────────────────────────────────────
 * 五張表中，音檔一律由 audio_asset 持有，其他表只存文字。
 * 同一段泰文不管在哪裡出現，都指向同一個檔案，只會被合成一次。
 * ──────────────────────────────────────────────────────────────────
 *
 * 本腳本可重複執行：所有建立動作都有存在性檢查，不會覆蓋既有資料表。
 * ★ 這個特性請維持住 —— 不要把 DROP TABLE 加進這個檔案。
 *   需要重建時用 db/reset-postgres.sql，那支才是會刪資料的。
 */

/* ============================================================
 * 1. translation_query —— 查詢結果快取
 *
 * Key 為「使用者輸入的原文 ＋ 翻譯方向 ＋ 說話者性別」三者的組合，
 * 不區分單字或句子。
 *
 * 這張表不持有音檔，音檔在 audio_asset。
 * ============================================================ */
CREATE TABLE IF NOT EXISTS translation_query
(
    -- 代理主鍵。子表需以外鍵參考，中文字串當外鍵佔用空間大且 join 較慢，
    -- 故另設流水號。
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,

    -- 使用者輸入的原文。前後空白於寫入前去除。
    -- 中翻泰時這裡是中文，泰翻中時這裡是泰文。
    source_text   VARCHAR(100)  NOT NULL,

    -- TranslationDirectionEnum：ZH_TO_TH / TH_TO_ZH
    -- 由 LanguageDetector 依輸入的字元範圍自動判斷，使用者不需要選。
    direction     VARCHAR(20)   NOT NULL,

    -- SpeakerGenderEnum：MALE / FEMALE
    --
    -- 泰文的自稱與句尾助詞都分性別（男 ผม/ครับ、女 ฉัน/ค่ะ），
    -- 所以同一句中文的男版與女版是兩句不同的泰文，必須各存一筆。
    --
    -- ★ 泰翻中沒有性別概念，該方向一律為 NULL。
    gender        VARCHAR(10)   NULL,

    -- 這句話的中文面與泰文面。
    --
    -- ★ source_text 必定與其中一面完全相同，這份重複是刻意的：
    --   source_text 專職當快取的鑰匙，另外兩欄專職表示「這句話的兩面」。
    --   混用的話，程式每次都要先判斷方向才知道哪個欄位裝什麼，很容易寫錯。
    --
    --   例：輸入「我想喝酒」（男）
    --       source_text  = 我想喝酒
    --       chinese_text = 我想喝酒          ← 與 source_text 相同
    --       thai_text    = ผมอยากดื่มเหล้าครับ
    --
    --       輸入「ผมอยากดื่มเหล้าครับ」
    --       source_text  = ผมอยากดื่มเหล้าครับ
    --       chinese_text = 我想喝酒
    --       thai_text    = ผมอยากดื่มเหล้าครับ ← 與 source_text 相同
    chinese_text  VARCHAR(500)  NOT NULL,
    thai_text     VARCHAR(500)  NOT NULL,

    -- 泰文的羅馬拼音（含聲調符號，如 chǎn、dùuem）
    romanization  VARCHAR(500)  NOT NULL,

    /*
     * 這筆查的是「一個詞」還是「一句話」，由 AI 在翻譯那一次順便判斷。
     * 前端拿它決定「各種說法」那顆按鈕要不要出現 ——
     * 句子沒有別種說法（見 OpenAiTranslationClient 的 VARIANT_PROMPT），
     * 讓使用者按一顆註定沒東西的按鈕沒有意義。
     *
     * ★ 刻意允許 NULL，而且 NULL 是有意義的第三種值：
     *     TRUE  → 是詞，顯示按鈕
     *     FALSE → 是句子，不顯示按鈕
     *     NULL  → 不知道（模型沒給，或這一列比這個欄位還早存進來），
     *             按鈕照常顯示
     *
     * ★ 所以這個欄位「不要」補 NOT NULL 或 DEFAULT。
     *   補了 DEFAULT FALSE 的話，2026-08-17 以前的舊資料會全部變成
     *   「是句子」，那些詞的各種說法按鈕會集體消失，而且不會有錯誤訊息。
     */
    is_word       BOOLEAN,

    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_translation_query PRIMARY KEY (id),

    /* ★★★ 這一行是本次遷移最危險的地方，改動前請先讀完 ★★★
     *
     * 快取命中判斷依據，同時防止重複寫入。
     *
     * SQL Server 的 UNIQUE 把 NULL 當成「一個值」來比對，所以
     * 「同一句泰文（gender 為 NULL）只會有一筆」自動成立。
     *
     * PostgreSQL 預設相反：每個 NULL 都被視為互不相同，
     * 於是 (source_text, direction, NULL) 可以重複無限多筆。
     *
     * 後果：每查一次泰翻中就新增一筆、每次都重新付錢給 OpenAI，
     *       而且畫面上完全看不出異常 —— 這是會安靜燒錢的那種 bug。
     *
     * NULLS NOT DISTINCT 讓 PostgreSQL 的行為與 SQL Server 一致。
     * 需要 PostgreSQL 15 以上。★ 不可省略這兩個字。
     */
    CONSTRAINT uq_translation_query_key
        UNIQUE NULLS NOT DISTINCT (source_text, direction, gender),

    CONSTRAINT ck_translation_query_direction
        CHECK (direction IN ('ZH_TO_TH', 'TH_TO_ZH')),

    CONSTRAINT ck_translation_query_gender
        CHECK (gender IS NULL OR gender IN ('MALE', 'FEMALE'))
);

/*
 * ★ 用「泰文」找逐詞拆解時要用到的索引。
 *
 * 「我想喝酒」和「我想要喝酒」是兩句不同的中文，會各自存一列（快取的鑰匙
 * 是原文），但 AI 翻出來的泰文常常一模一樣。點「逐詞拆解」時就是拿泰文
 * 來這張表找「有沒有人已經拆過同一句泰文」，有的話直接撿現成的，
 * 不必再付一次錢重拆。
 *
 * ★ 沒有這個索引的話那個查詢會整表掃描。資料少的時候看不出來，
 *   累積到幾千筆之後每點一次逐詞都會慢一拍 —— 而且不會有任何錯誤訊息。
 *
 * 對應 TranslationSegmentRepository.findByThaiTextOrderBySeqNo。
 */
CREATE INDEX IF NOT EXISTS ix_translation_query_thai_text
    ON translation_query (thai_text);

/*
 * ★ 補欄位給「已經存在」的資料庫（2026-08-17）。
 *
 * 上面那段 CREATE TABLE 寫的是 IF NOT EXISTS，所以在早就建好表的環境
 * （你的本機、正式的 Cloud SQL）它整段會被跳過 —— 新加的 is_word
 * 永遠不會出現。程式一啟動就會在寫入時炸掉，說找不到這個欄位。
 *
 * ADD COLUMN IF NOT EXISTS 讓這一行在兩種環境都安全：
 *   新資料庫 → 上面已經建好了，這行什麼也不做
 *   舊資料庫 → 這行把欄位補上，既有資料保持 NULL（代表「不知道」）
 */
ALTER TABLE translation_query
    ADD COLUMN IF NOT EXISTS is_word BOOLEAN;

/* ============================================================
 * 2. translation_segment —— 逐詞拆解結果
 *
 * 複合主鍵 (query_id, seq_no)，無獨立流水號。
 * 同一個詞會在不同句子的拆解中重複出現，這是正確的 ——
 * 本表記錄的是「該句話如何拆解」，而非字典。
 *
 * 兩個方向共用同一組欄位：
 *   中翻泰 → chinese_text 是輸入的詞，thai_text 是翻出來的
 *   泰翻中 → thai_text 是輸入的詞，chinese_text 是翻出來的
 *
 * ★ 泰文的句尾助詞（ครับ、ค่ะ、นะ）沒有中文意思，
 *   chinese_text 會存一個括號標籤，例如「（男性禮貌語助詞）」。
 *   不可以因為翻不出中文就把它從拆解結果裡拿掉 ——
 *   那些是泰文最高頻的字，使用者正需要知道它們在做什麼。
 * ============================================================ */
CREATE TABLE IF NOT EXISTS translation_segment
(
    query_id      BIGINT        NOT NULL,

    -- 顯示順序，自 1 起算
    seq_no        INT           NOT NULL,

    chinese_text  VARCHAR(50)   NOT NULL,
    thai_text     VARCHAR(100)  NOT NULL,
    romanization  VARCHAR(100)  NOT NULL,

    CONSTRAINT pk_translation_segment PRIMARY KEY (query_id, seq_no),

    -- 資料庫層級的完整性約束。
    -- 注意：程式端刻意不使用 JPA 關聯註解（@ManyToOne 等），
    -- 關聯由 Service 層自行查詢組裝，此約束僅確保資料不會孤立。
    CONSTRAINT fk_translation_segment_query_id
        FOREIGN KEY (query_id)
        REFERENCES translation_query (id)
        ON DELETE CASCADE
);

/* ============================================================
 * 3. vocabulary —— 單字表
 *
 * ★ 一列代表「一個說法」，不是「一個詞」。
 *   泰文的「我」至少有 ผม / ฉัน / กู 三種說法，所以「我」會佔三列。
 *   單字列表頁因此會出現同一個中文詞連續多列 —— 那是預期行為。
 *
 * ★ 這張表不兼任「省錢用的快取」。
 *   曾經 TranslationService 會先查這裡、命中就不呼叫 AI，
 *   那條捷徑會讓多重說法功能永遠失效（查過「我想喝酒」之後，
 *   單獨查「我」就只會拿到 ฉัน，永遠問不到 ผม 和 กู）。該捷徑已移除，
 *   不可加回來。
 * ============================================================ */
CREATE TABLE IF NOT EXISTS vocabulary
(
    id            BIGINT        GENERATED BY DEFAULT AS IDENTITY,

    chinese_text  VARCHAR(50)   NOT NULL,
    thai_text     VARCHAR(100)  NOT NULL,
    romanization  VARCHAR(100)  NOT NULL,

    -- GenderUsageEnum：MALE / FEMALE / BOTH。這個「說法」適合誰用。
    --
    -- ★ 與 translation_query.gender 是不同的概念：
    --   那個是「使用者是誰」，這個是「這個說法適合誰」，
    --   而且只有這裡才有 BOTH（使用者不可能男女都是，
    --   但一個詞可以是男女通用的，例如 กู）。
    --
    -- 從句子拆解沉澱下來的詞沒有這項資訊，為 NULL。
    -- 日後單獨查詢該詞時會補上（合併規則見 TranslationPersistenceService）。
    gender_usage  VARCHAR(10)   NULL,

    -- PolitenessEnum：FORMAL / NEUTRAL / CASUAL / RUDE
    -- 前端要把 RUDE 用警示色標出來 ——
    -- 用錯場合的後果是冒犯到人，不是講得不夠好。
    politeness    VARCHAR(10)   NULL,

    -- 中文說明，例如「男生自稱，正式或對不熟的人使用」
    note          VARCHAR(200)  NULL,

    -- VocabularySourceTypeEnum：SEGMENT（由句子拆解而來）/ DIRECT（直接查此詞）
    -- 已存在的列不更新此欄位，以首次寫入的值為準。
    source_type   VARCHAR(20)   NOT NULL,

    created_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at    TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_vocabulary PRIMARY KEY (id),

    -- 字典的唯一鍵。★ 是中文＋泰文的組合，這一點才讓同一個詞能存多種說法。
    -- 兩個欄位都是 NOT NULL，所以此處不需要 NULLS NOT DISTINCT。
    CONSTRAINT uq_vocabulary_chinese_thai
        UNIQUE (chinese_text, thai_text),

    CONSTRAINT ck_vocabulary_source_type
        CHECK (source_type IN ('SEGMENT', 'DIRECT')),

    CONSTRAINT ck_vocabulary_gender_usage
        CHECK (gender_usage IS NULL
               OR gender_usage IN ('MALE', 'FEMALE', 'BOTH')),

    CONSTRAINT ck_vocabulary_politeness
        CHECK (politeness IS NULL
               OR politeness IN ('FORMAL', 'NEUTRAL', 'CASUAL', 'RUDE'))
);

-- 查一個中文詞的所有說法時會用到（單字查詢的主要路徑）。
CREATE INDEX IF NOT EXISTS ix_vocabulary_chinese_text
    ON vocabulary (chinese_text);

/* ============================================================
 * 4. audio_asset —— 音檔資產
 *
 * 規則只有一句話：★ 同一段文字，全站只會有一個音檔 ★
 *
 * 為什麼要這樣設計：合成語音要付錢。如果音檔綁在「那一次查詢」身上，
 * 同一個 เหล้า 會被合成好幾次 —— 查「酒」一次、查「我想喝酒」逐詞一次、
 * 查「他喝酒了」又一次。三個一模一樣的檔案，付了三次錢。
 *
 * 改成以文字內容為鍵之後，查得越多、覆蓋率越高，語音費用趨近於零。
 * 這是本專案「用越久越省錢」的核心。
 *
 * ★ 語言欄位是必要的：中文和泰文各自有自己的音檔，
 *   存在不同的子資料夾（audio/th、audio/zh）。
 * ============================================================ */
CREATE TABLE IF NOT EXISTS audio_asset
(
    id          BIGINT        GENERATED BY DEFAULT AS IDENTITY,

    -- 要唸出來的文字。可能短到一個詞（เหล้า），長到一整句。
    speech_text VARCHAR(500)  NOT NULL,

    -- SpeechLanguageEnum：TH / ZH
    language    VARCHAR(10)   NOT NULL,

    -- 相對於 audio 資料夾的路徑，例如 th/a1b2c3d4e5f6.wav。
    -- 前端把它接在 /audio/ 後面就是可以直接播放的網址。
    file_path   VARCHAR(100)  NOT NULL,

    created_at  TIMESTAMP     NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_audio_asset PRIMARY KEY (id),

    -- ★ 這條唯一鍵就是「同一段文字只合成一次」的保證。
    --   拿掉它程式仍然會跑，只是會安靜地一直重複付錢，
    --   而且畫面上完全看不出異常。務必保留。
    --   兩個欄位都是 NOT NULL，不需要 NULLS NOT DISTINCT。
    CONSTRAINT uq_audio_asset_text_language
        UNIQUE (speech_text, language),

    CONSTRAINT ck_audio_asset_language
        CHECK (language IN ('TH', 'ZH'))
);

/* ============================================================
 * 5. api_usage_log —— API 用量與費用紀錄
 *
 * 事件紀錄表，無自然鍵。屬營運監控資料，刪除不影響業務功能。
 * ============================================================ */
CREATE TABLE IF NOT EXISTS api_usage_log
(
    id                  BIGINT         GENERATED BY DEFAULT AS IDENTITY,

    -- 對應的查詢，可追溯。
    -- 刻意「不」建立外鍵約束：用量紀錄於呼叫外部服務的當下寫入，
    -- 此時 translation_query 尚未寫入（外部呼叫在交易之外執行），
    -- 建立外鍵會導致寫入失敗。同時本表為稽核用途，
    -- 即使對應的查詢日後被刪除，紀錄仍應保留。
    query_id            BIGINT         NULL,

    -- AiProviderEnum：OPENAI / ANTHROPIC / GOOGLE / AZURE
    provider            VARCHAR(20)    NOT NULL,

    -- AiServiceTypeEnum：TRANSLATION / SPEECH
    service_type        VARCHAR(20)    NOT NULL,

    model_name          VARCHAR(100)   NOT NULL,

    -- UsageUnitTypeEnum：TOKEN（對話模型）/ CHARACTER（語音合成）
    unit_type           VARCHAR(20)    NOT NULL,

    input_units         BIGINT         NOT NULL,

    -- 語音服務無輸出計價，固定為 0
    output_units        BIGINT         NOT NULL,

    -- 呼叫「當下」的單價。價格調整後歷史紀錄仍可驗算。
    -- 金額一律使用 NUMERIC，Java 端對應 BigDecimal，
    -- 禁止使用 float / double，否則累加後金額會有誤差。
    input_unit_price    NUMERIC(12,8)  NOT NULL,
    output_unit_price   NUMERIC(12,8)  NOT NULL,
    cost_amount         NUMERIC(12,6)  NOT NULL,

    -- 固定 USD。不存台幣，匯率浮動，統計時再換算。
    currency            CHAR(3)        NOT NULL DEFAULT 'USD',

    -- PostgreSQL 有原生的 BOOLEAN，不需要 SQL Server 那套 BIT。
    -- 失敗仍可能計費，且保留紀錄才能觀察失敗率。
    is_success          BOOLEAN        NOT NULL,

    created_at          TIMESTAMP      NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT pk_api_usage_log PRIMARY KEY (id),

    CONSTRAINT ck_api_usage_log_service_type
        CHECK (service_type IN ('TRANSLATION', 'SPEECH')),

    CONSTRAINT ck_api_usage_log_unit_type
        CHECK (unit_type IN ('TOKEN', 'CHARACTER'))
);

-- 期間統計用（例如「這個月花了多少」）
CREATE INDEX IF NOT EXISTS ix_api_usage_log_created_at
    ON api_usage_log (created_at);

-- 追溯某次查詢花了多少錢
CREATE INDEX IF NOT EXISTS ix_api_usage_log_query_id
    ON api_usage_log (query_id);


/* ============================================================
 * 執行方式
 * ============================================================
 *
 * 【本機】
 *   docker cp db\schema.sql language-project-postgres:/tmp/schema.sql
 *   docker exec language-project-postgres psql -U postgres -d language_project -f /tmp/schema.sql
 *
 * 【重新建立】
 *   本腳本不會覆蓋既有資料表，直接重跑不會清掉任何東西。
 *   要真的重建，先執行 db\reset-postgres.sql（那支才會 DROP），再回來跑這一支。
 *
 *   ★ 不要把 DROP TABLE 加進這個檔案。
 *     「可重複執行且不刪資料」是這個腳本的安全特性。
 *
 * 【音檔資料夾】
 *   本機開發時，專案根目錄下需有 audio\th\ 與 audio\zh\ 兩個資料夾。
 *   雲端不需要，音檔在 Cloud Storage。
 */
